### ISSUE TITLE
Improve user experience for deployment and upgrading

### ISSUE THREAD

**Issue by Shulyaka** [gentoomaniac/minigal-nano-ng#23]
Hi,

This is something I'd like do discuss with you first before implementing.
I'd like to move everything from src/ dir to the upper level. That would allow users to just git clone the gallery directly into the web server directory to start using it right away. Now one needs to clone it to another directory, then copy src to the web server directory. And for upgrading one needs to do it again. There is not that much at the top level currently (just readme and changelog) so I don't think that we really need a separate src/ for everything else directory at the cost of user experience.
Please advise if I can proceed with that.

Further, after someone have installed the gallery, I think there is no need to force a user to do a system check and create a configuration. Here is my proposal:
1. A user have git-cloned the gallery into a new directory.
2. If we detect that the 'photo' directory does not exists or empty, we consider him a new user, show some help on how to get started and perform system checks.
3. If there are photos, then we consider a user as experienced, know that he has read the readme and knows how to add photos, configure or perhorm system checks. We present a working gallery with default configuration in that case even if it's a new installation.
Please advise if you agree with this also.

**Comment by gentoomaniac** [comment]
just back from holiday so i didn't look too much into it yet.

on the first point:
i guess that's fine. the idea for a source directory doesn't make much sense here as probably there will hardly ever be additional files which are not directly related to the source.
so let's move everything.

on the second topic:
when reading your comment it brings up another thing which is bugging me. the template system.
i think this kind of behaviour should be controlled by the templates as i think it's highly personal preference (besides what we chose as a default)

so my personal preference would be to fix the template system and then do a rewrite of the default templates which would then implement something like you suggested.

I'd like to see an info box where now the gallery is which just links to the checks. a bit like the Google upload picture dialogues.

**Comment by Shulyaka** [comment]
Hope you had a great holiday!

on the first point:
OK, I will create a new pull request it as soon as you merge the two pending (and yet another for better mobile support that I have already started on top of them) to not interfere.

on the second point:
Sorry, I am not sure I have fully understood your proposal. Do you suggest to create default template that will ask the user to change the default template to something different? I think it is a good idea, but I just want to double check if that is what you meant:)
What do you think is broken with the template system?

**Comment by gentoomaniac** [comment]
1) Will take care of this in a moment ;)

2) There is no template system ;) The "template" is a very dumb regex replace.
The outcome is that the main code generates already HTML which is a big flaw as you can't fully customize the page.
Think about e template which lists all images in a grid without pagination. This won't be possible as you don't get the plain data, but already generated HTML tables.
IMO this needs to be resolved. When that is done the templates will be a lot more flexible.

As an example see my other project https://github.com/gentoomaniac/py-simplegal
In that case the whole application is written in the templating system + HTML/JQuery etc.
Everything else is only providing data and or rendering the template files.

This is something I'd like to have in this project as well.

**Comment by Shulyaka** [comment]
Thanks for merging! Feel free to implement your vision of template system)
